name: Wiki Test

on:
  gollum: 
  
#gollum is the GitHub event that fires when someone creates or updates a wiki page in the repo.

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: List Wiki files
        run: |
          ls -la wiki

      - name: Show Home page
        run: |
          cat wiki/Home.md
  
